dev

diff --git a/.github/workflows/owasp-zap.yml b/.github/workflows/owasp-zap.yml
--- a/.github/workflows/owasp-zap.yml
+++ b/.github/workflows/owasp-zap.yml
@@ -23,21 +23,31 @@ jobs:
         uses: zaproxy/action-baseline@v0.14.0
         with:
           target: 'https://latticenepal.com'  # Target web application
-          cmd_options: '-a -r /zap/wrk/zap_report.html' # Corrected path for report
+          cmd_options: '-a -r zap_report.html -w report_md.md' # Corrected path for report
           allow_issue_writing: false          # Disable issue creation to avoid rate limits
 
-      - name: Verify Report File
+      - name: Verify Report Files
         run: |
           if [ ! -f "/zap/wrk/zap_report.html" ]; then
             echo "Error: zap_report.html not found in the volume path!"
+            exit 1
+          fi
+          if [ ! -f "/zap/wrk/report_md.md" ]; then
+            echo "Error: report_md.md not found in the volume path!"
             exit 1
           fi
 
       - name: List Files in Volume Path
         run: ls -l /zap/wrk
 
-      - name: Upload ZAP Report
+      - name: Upload ZAP HTML Report
         uses: actions/upload-artifact@v3
         with:
-          name: ZAP Report
+          name: ZAP HTML Report
           path: /zap/wrk/zap_report.html
+
+      - name: Upload ZAP Markdown Report
+        uses: actions/upload-artifact@v3
+        with:
+          name: ZAP Markdown Report
+          path: /zap/wrk/report_md.md
